export { ReactComponent as IconComment } from './comment.svg'
export { ReactComponent as IconEmail } from './email.svg'
export { ReactComponent as IconLocation } from './location.svg'
export { ReactComponent as IconName } from './name.svg'
export { ReactComponent as IconPhone } from './phone.svg'
